# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
              users: 
                test:
                  password: $2y$10$oAbcAqd6X4x2nsTvnE1aouH1xYf8MfQeqbmjJxZTf2E3zAGRys2QC
                  roles: ROLE_ADD_PRODUCT
                example:
                  password: $2y$10$AWp7uhjbWOYA5L0mUvLxcu6K4AUTelMw6ys7lam3qr.o9LT/AXQ6C
                  roles: ROLE_ADD_PRODUCT
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login: 
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
            logout_on_user_change: true
    access_control:
        - { path: ^/admin, roles: ROLE_ADD_PRODUCT }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 10